#!/bin/sh

accum=''

add()
{
    local s="$1"

    s=`echo "$s" | sed -e 's|"|\\"|g'`
    if [ -z "$accum" ] ; then
	accum="\"$s\""
    else
	accum="$accum, \"$s\""
    fi
}

emit()
{
    echo "[ $accum ]"
}

if [ $# -gt 0 ]; then
    for s in "$@" ; do
	add "$s"
    done
else
    while read s ; do
	add "$s"
    done
fi
emit
